name: dolphin_click
channels:
  - conda-forge
dependencies:
  - absl-py=2.3.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - fonttools=4.59.0
  - freetype=2.13.3
  - h5py=3.14.0
  - hdf5=1.14.6
  - icu=75.1
  - keras=3.10.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - markdown-it-py=3.0.0
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - mdurl=0.1.2
  - ml_dtypes=0.5.1
  - munkres=1.1.4
  - namex=0.1.0
  - ncurses=6.5
  - openjpeg=2.5.3
  - openssl=3.5.2
  - optree=0.17.0
  - packaging=25.0
  - pandas=2.3.1
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pygments=2.19.2
  - pyparsing=3.2.3
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.2
  - rich=14.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - tk=8.6.13
  - tornado=6.5.1
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.3.0
      - audioread==3.0.1
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - comm==0.2.3
      - debugpy==1.8.16
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.2
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - fsspec==2025.7.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - iniconfig==2.1.0
      - ipykernel==6.30.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - lark==1.2.2
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.11.0
      - llvmlite==0.44.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==2.1.3
      - openai==1.106.1
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - pooch==1.8.2
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pytest==8.4.2
      - python-json-logger==3.3.0
      - pyyaml==6.0.2
      - pyzmq==27.0.2
      - referencing==0.36.2
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.0
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==0.5.0.post1
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20250822
      - typing-inspection==0.4.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
